# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install debootstrap
        run: |
          sudo apt-get update
          sudo apt-get -y install debootstrap qemu-user-static

      # Runs a set of commands using the runners shell
      - name: build chroot
        run: |
          mkdir chroot-armhf
          sudo debootstrap --no-check-gpg --arch=armhf --variant=buildd focal chroot-armhf http://ports.ubuntu.com/ubuntu-ports
          sudo mount -t proc /proc chroot-armhf/proc
          sudo mount --rbind /sys chroot-armhf/sys
          sudo mount --rbind /dev chroot-armhf/dev
          sudo chroot chroot-armhf /debootstrap/debootstrap --second-stage
          sudo chroot chroot-armhf /bin/bash
          ls
